///stop_music();
audio_stop_sound(mus_overworld1_intro);
audio_stop_sound(mus_overworld1);
audio_stop_sound(mus_bonus_intro);
audio_stop_sound(mus_bonus);
audio_stop_sound(mus_cave);
audio_stop_sound(mus_night);
audio_stop_sound(mus_forest_start);
audio_stop_sound(mus_forest);
